# konfigurační proměnné pro všechny soubory

# soubor ipc-dynamic-meas-240419_210554.log
# 0:0:27:447747 start - prvni strom za sloupem (0)
# 0:0:55:150641 prvni strom za dalsim sloupem (1)
# 0:1:22:453993 sloup 2
# 0:1:23:318242 prvni strom za dalsim sloupem (2)
# 0:1:48:535941 sloup 3
# 0:1:49:266865 prvni strom za dalsim sloupem (3)

#
# cesta k logu, který má být analyzován
log_file : data/ipc-dynamic-meas-240419_210554.log

#Zvolené časové rozmezi z logu v sekundách
res1 : 27
res2 : 109



